config/routes.rb
LineAccess::Application.routes.draw do
  get "layout_builder/create"

  get "layout_builder/destroy"

  get "layout_builder/update"

  
  get "metric/show"
  get "metric/logInJSON"
  post "metric/logInJSON"
  get "metric/execJSON"
  post "metric/execJSON"

  match '/glasses/jarvixInterpreter', :controller => 'glasses', :action => 'jarvixInterpreter'
  resources :glasses

  resources :smartwatches

  match '/summaries/setLocation', :controller => 'summaries', :action => 'setLocation'
  match '/summaries/geoSettings', :controller => 'summaries', :action => 'geoSettings'
  match '/summaries/simulateMe', :controller => 'summaries', :action => 'simulateMe'
  match '/summaries/newOrigin', :controller => 'summaries', :action => 'newOrigin'
  match '/summaries/sendToAll', :controller => 'summaries', :action => 'sendToAll'
  match '/bot/callback', :controller => 'anet_devices', :action => 'fbbot'
  get '/summaries/call/:id', :controller => 'summaries', :action => 'showCallContents'
  match '/logout', :controller => 'summaries', :action => 'logout'
  resources :summaries

  
  resources :accounts

  resources :earthquakes

  resources :subscriptions

  resources :community

  resources :anet_logs

  resources :feed_readers

  resources :anet_values

  resources :anet_commands

  resources :dashboards

  get '/devices/claim', :controller=>'anet_devices', :action=> 'showClaim'
  get '/devices/add_board', :controller=>'anet_devices', :action=> 'showAdd'
  get '/devices/add_phone', :controller=>'anet_devices', :action=> 'showPhone'
  get '/devices/add_swatch', :controller=>'anet_devices', :action=> 'showSWatch'
  get '/devices/browser/:device', :controller=>'anet_devices', :action=> 'showBrowser'
  post '/devices/open/:device', :controller=>'anet_devices', :action=> 'showOpenFile'
  post '/devices/save/:device', :controller=>'anet_devices', :action=> 'showSaveFile'
  post '/devices/sync', :controller=>'anet_devices', :action=> 'alexa_sync'
  post '/devices/scan', :controller=>'anet_devices', :action=> 'alexa_scanning'
  post '/devices/dhcp', :controller=>'anet_devices', :action=> 'dhcp_process'
  match '/devices/send', :controller => 'anet_devices', :action => 'communication'
  match '/devices/camera/download', :controller => 'anet_devices', :action => 'camera_download'
  post '/devices/schedule', :controller=>'anet_devices', :action=> 'manage_schedule'
  match '/devices/pubsub', :controller=>'anet_devices', :action=> 'manage_pubsub'
  resources :anet_devices do
      post :sendToDevice, on: :collection 
  end
  
  resources :sys_user_phones

  resources :personal_accounts do
    post :changeLanguage, on: :collection
    post :likeIt, on: :collection
  end

  resources :authentications
  match '/auth/signup', :controller => 'authentications', :action => 'signup'
  get '/auth/signup/backwards', :controller => 'authentications', :action => 'backwards'
  match '/auth/webLogin', :controller => 'authentications', :action => 'webLogin'
  
  match '/auth/tokenize', :controller => 'authentications', :action => 'google_tokenize'
  match '/auth/v2/alexa/tokenize', :controller => 'authentications', :action => 'alexa_tokenize'
  post '/auth/cookie', :controller => 'authentications', :action => 'internal_token'
  match '/auth/assistant', :controller => 'authentications', :action => 'google_auth'
  match '/auth/alexapoc', :controller => 'authentications', :action => 'alexa_poc'
  match '/auth/alexa', :controller => 'authentications', :action => 'alexa_auth'
  get '/auth/messengerbot', :controller => 'authentications', :action => 'messenger_auth'
  post '/auth/messengerbot', :controller => 'authentications', :action => 'messenger_messages'
  match '/auth/:provider/callback' => 'authentications#create'

  get "/policy", to: "welcome#policy"
  get "/policy-es", to: "welcome#policy-es"

  match '/auth/v2/login', :controller => 'authentications', :action => 'loginv2'
  match '/auth/v2/verify', :controller => 'authentications', :action => 'internal_token'
  post '/auth/v2/user/avatar', :controller => 'authentications', :action => 'post_avatar_v2'
  post '/auth/v2/user/forgot', :controller => 'authentications', :action => 'post_forgot_v2'
  get '/auth/v2/user', :controller => 'authentications', :action => 'get_user_v2'
  put '/auth/v2/user', :controller => 'authentications', :action => 'put_user_v2'
  put '/auth/v2/user/pwd', :controller => 'authentications', :action => 'put_user_pwd_v2'
  match '/devices/v2/show', :controller=>'anet_devices', :action=> 'get_devices_v2'
  match '/devices/v2/recent_activity', :controller=>'anet_devices', :action=> 'get_recent_activity_v2'
  match '/location/v2/update', :controller=>'summaries', :action=> 'set_location_v2'
  match '/devices/v2/command/alexa', :controller=>'anet_devices', :action=> 'receive_alexa_payload_v2'
  match '/devices/v2/command/nest', :controller=>'anet_devices', :action=> 'receive_nest_payload_v2'
  match '/devices/v2/command/google', :controller=>'anet_devices', :action=> 'receive_google_payload_v2'
  match '/devices/v2/command/send', :controller=>'anet_devices', :action=> 'receive_api_payload_v2'
  match '/devices/v2/command/sendv2', :controller=>'anet_devices', :action=> 'sendToDevicev2'
  match '/devices/v2/public', :controller=>'anet_devices', :action=> 'get_public_devices_v2'
  match '/webhook/v2/from_email', :controller=>'anet_devices', :action=> 'receive_email_payload_v2'
  match '/assistant/v2/activity', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  post '/assistant/v2/link', :controller=>'authentications', :action=> 'post_assistant_link_v2'
  get '/assistant/v2/link', :controller=>'authentications', :action=> 'get_assistant_link_v2'
  match '/energy/v2/consumption/1day', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/7day', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/1month', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/12months', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/test/v2/test_1', :controller=>'anet_devices', :action=> 'random_test_v2'
  match '/test/v2/test_2', :controller=>'authentications', :action=> 'random_test2_v2'
  match '/devices/v2/:token/logs', :controller=>'anet_devices', :action=> 'get_device_logs_v2'
  post  '/devices/v2/:token/schedule', :controller=>'anet_devices', :action=> 'manage_schedule'
  post  '/devices/v2/:token/command', :controller=>'anet_commands', :action=> 'create'
  get  '/devices/v2/:token/status', :controller=>'anet_devices', :action=> 'get_status_v2'
  get  '/devices/v2/:token/state', :controller=>'anet_devices', :action=> 'get_state_v2'
  get  '/devices/v2/:token/screensaver', :controller=>'anet_devices', :action=> 'get_screensaver_v2'
  post  '/devices/v2/:token/screensaver', :controller=>'anet_devices', :action=> 'post_screensaver_v2'
  get  '/devices/v2/:token/props', :controller=>'anet_devices', :action=> 'get_props_v2'
  get  '/devices/v2/:token/prop/:id', :controller=>'anet_devices', :action=> 'get_prop_v2'
  get  '/devices/v2/:token/prop/:id/chart', :controller=>'anet_devices', :action=> 'get_prop_chart_v2'
  get  '/devices/v2/:token/prop/:id/chart/24hour', :controller=>'anet_devices', :action=> 'get_prop_chart_24h_v2'
  get  '/devices/v2/:token/prop/:id/chart/7day', :controller=>'anet_devices', :action=> 'get_prop_chart_7day_v2'
  get  '/devices/v2/:token/prop/:id/chart/monthly', :controller=>'anet_devices', :action=> 'get_prop_chart_month_v2'
  get  '/devices/v2/:token/command/show', :controller=>'anet_commands', :action=> 'show'
  get  '/devices/v2/:token/schedule/show', :controller=>'anet_devices', :action=> 'get_schedules_v2'
  delete  '/devices/v2/:token/schedule/:id', :controller=>'anet_devices', :action=> 'delete_schedule_v2'
  delete  '/devices/v2/:token/command/:id', :controller=>'anet_commands', :action=> 'destroy'
  post  '/layouts/v2', :controller=>'layout_builder', :action=> 'create'
  get  '/layouts/v2', :controller=>'layout_builder', :action=> 'show'
  delete  '/layouts/v2/:id', :controller=>'layout_builder', :action=> 'destroy'
  put  '/layouts/v2/:id', :controller=>'layout_builder', :action=> 'update'
  post  '/devices/v2/:token/fav', :controller=>'anet_devices', :action=> 'post_fav_v2'
  get  '/devices/v2/favs', :controller=>'anet_devices', :action=> 'get_fav_v2'
  post '/devices/v2/state/alexa', :controller=>'anet_devices', :action=> 'alexa_state_report_v2'
  get '/devices/v2/:token/state/suitch', :controller=>'anet_devices', :action=> 'suitch_state_report_v2'
  get '/edgar/test', :controller=>'anet_devices', :action=> 'test_api'
  post  '/chain/v2', :controller=>'chain_reaction', :action=> 'create'
  get  '/chain/v2', :controller=>'chain_reaction', :action=> 'show'
  delete  '/chain/v2/:id', :controller=>'chain_reaction', :action=> 'destroy'
  put  '/chain/v2/:id', :controller=>'chain_reaction', :action=> 'update'

  get '/devices/ssid/availables', :controller=>'anet_devices', :action=> 'getAvailableDevicePerSsid'
  post '/devices/ssid/owner', :controller=>'anet_devices', :action=> 'setIdOwnerToDevices'

  get '/devices/notifications', :controller=>'anet_devices', :action=> 'getDeviceNotifications'
  post '/devices/notifications/dismiss', :controller=>'anet_devices', :action=> 'post_notifications_dismiss'

  post '/devices/v2/findmy/create', :controller=>'anet_devices', :action=> 'findmy_create'
  post '/devices/v2/findmy/sensor', :controller=>'anet_devices', :action=> 'findmy_create_sensor'
  get '/devices/v2/findmy/all', :controller=>'anet_devices', :action=> 'get_findmy_all'
  get '/devices/v2/findmy/sensors', :controller=>'anet_devices', :action=> 'get_findmy_sensors'
  post '/devices/v2/findmy/located', :controller=>'anet_devices', :action=> 'findmy_located'
  get '/devices/v2/findmy/:token/soil', :controller=>'anet_devices', :action=> 'get_findmy_soil'

app/models/personal_account.rb
class PersonalAccount < ActiveRecord::Base
  attr_accessible :note, :sound_file, :user_id
end

app/controllers/personal_accounts_controller.rb
require 'rubygems'
# require 'bing_translator'
require 'sys_phrases.rb'
require 'sys_region.rb'
require 'sys_region_lang.rb'
require 'sys_user_phone.rb'
require 'sys_phone_type.rb'
require 'api_interface.rb'
require 'api_interface.rb'
require 'sys_user.rb'
require 'anet_device.rb'
require 'likes.rb'

class PersonalAccountsController < ApplicationController
  # GET /personal_accounts
  # GET /personal_accounts.json
  def index
    @sys_user_phone=SysUserPhone.new
    @anet_device=AnetDevice.new
    if session[:activeUser]==nil
      redirect_to "/auth/facebook"
      return
    end
    attachDevices()
    # traemos 10 dispositivos nuevos que esten abiertos
    @open_devices=AnetDevice.where(:is_public=>1)
    @personal_accounts = Sys_Phrase.all
    @registeredInterfaces=Api_Interface.where("visible=1")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @personal_accounts }
    end
  end

  # GET /personal_accounts/1
  # GET /personal_accounts/1.json
  def show
    redirect_to "/personal_accounts"
    return
    if session[:activeUser]==nil
      redirect_to "/"
      return
    end
    @personal_account = Sys_Phrase.find(params[:id])
    @registeredInterfaces=Api_Interface.where("visible=1")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @personal_account }
    end
  end

  # GET /personal_accounts/new
  # GET /personal_accounts/new.json
  def new
    redirect_to "/personal_accounts"
    return
    @personal_account = Sys_Phrase.new
    @registeredInterfaces=Api_Interface.where("visible=1")
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @personal_account }
    end
  end

  # GET /personal_accounts/1/edit
  def edit
    redirect_to "/personal_accounts"
    return
    @registeredInterfaces=Api_Interface.where("visible=1")
    @personal_account = Sys_Phrase.find(params[:id])
  end

  # POST /personal_accounts
  # POST /personal_accounts.json
  def create
    redirect_to "/personal_accounts"
    return
    @registeredInterfaces=Api_Interface.where("visible=1")
    @personal_account = Sys_Phrase.new(params[:personal_account])

    respond_to do |format|
      if @personal_account.save
        format.html { redirect_to @personal_account, notice: 'Personal account was successfully created.' }
        format.json { render json: @personal_account, status: :created, location: @personal_account }
      else
        format.html { render action: "new" }
        format.json { render json: @personal_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /personal_accounts/1
  # PUT /personal_accounts/1.json
  def update
    redirect_to "/personal_accounts"
    return
    @registeredInterfaces=Api_Interface.where("visible=1")
    @personal_account = Sys_Phrase.find(params[:id])

    respond_to do |format|
      if @personal_account.update_attributes(params[:personal_account])
        format.html { redirect_to @personal_account, notice: 'Personal account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @personal_account.errors, status: :unprocessable_entity }
      end
    end
  end

  #this changes the language of the spoken user
  def changeLanguage
    puts params.inspect
    if session[:activeUser]==nil
      redirect_to "/auth/facebook"
      return
    end
    session[:activeUser].lang=params[:lang]
    currentUser=Sys_User.find_by_id(session[:activeUser].id)
    currentUser.lang=params[:lang]
    currentUser.save
    session[:activeUser]=currentUser
    redirect_to "/personal_accounts"
    return
  end

  def likeIt
    if session[:activeUser]==nil
      redirect_to "/login"
      return
    end
    myLike=Likes.where(:user_liked=>session[:activeUser].id)
    if myLike.length>0
      #entonces ya hay un like ahi, solo lo vamos a quitarle el like
      myLike.each do |singleLike|
        singleLike.destroy
      end
    else
      ilikeit=Likes.new(:device_id=>params[:deviceid],:user_liked=>session[:activeUser].id)
      ilikeit.save
    end
    render :nothing => true, :status => 200
  end
  # DELETE /personal_accounts/1
  # DELETE /personal_accounts/1.json
  def destroy
    redirect_to "/personal_accounts"
    return
    @registeredInterfaces=Api_Interface.where("visible=1")
    @personal_account = Sys_Phrase.find(params[:id])
    @personal_account.destroy

    respond_to do |format|
      format.html { redirect_to personal_accounts_url }
      format.json { head :no_content }
    end
  end

  def logmeout
    puts "--------------LOG OUT-----------"
  end
end

app/helpers/personal_accounts_helper.rb
module PersonalAccountsHelper
end

app/views/personal_accounts/_form.html.erb
<%= form_for(@personal_account) do |f| %>
  <% if @personal_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal_account.errors.count, "error") %> prohibited this personal_account from being saved:</h2>

      <ul>
      <% @personal_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :sound_file %><br />
    <%= f.text_field :sound_file %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personal_accounts/_thirdparties.html.erb
<div class="modal fade" id="modal-pair-telegram">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"><%= t(:telegram_pairing) %><i class="icon-twitter"></i></h4> 
  </div>
    <div class="modal-body">
      <p style="float: left;margin-top:-30px"><img src="/images/240px-Telegram_2019_Logo.svg.png" width="100px" height="100px" style="top:-30px"></p>
<p><%= t(:telegram_permission_content) %></p>
<p style="font-size:30px"><strong><%= session[:activeUser].user_id.split("-")[0] %><strong/></p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:not_now) %></a>
      <!-- a href="" class="btn btn-primary"><%= t(:lets_go) %></a -->
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div>
  <div class="modal fade" id="modal-pair-facebook-bot">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><%= t(:facebook_pairing) %><i class="icon-twitter"></i></h4> 
    </div>
      <div class="modal-body">
        <p style="float: left;margin-top:-30px"><img src="/images/f_logo_RGB-Blue_72.png" width="100px" height="100px" style="top:-30px"></p>
  <p><%= t(:facebook_permission_content) %></p>
  <p style="font-size:30px"><strong>anet_<%= session[:activeUser].user_id.split("-")[0] %><strong/></p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:not_now) %></a>
        <a href="https://www.facebook.com/suitch.co/" class="btn btn-primary"><%= t(:lets_go) %></a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
  <div class="modal fade" id="modal-pair-twitter">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><%= t(:twitter_pairing) %><i class="icon-twitter"></i></h4> 
    </div>
      <div class="modal-body">
        <p style="float: left;margin-top:-30px"><img src="https://abs.twimg.com/a/1373698031/images/resources/twitter-bird-light-bgs.png" width="100px" height="100px" style="top:-30px"></p>
  <p><%= t(:twitter_permission_content) %></p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:not_now) %></a>
        <a href="/auth/twitter" class="btn btn-primary"><%= t(:lets_go) %></a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modal-pair-evernote">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><%= t(:evernote_pairing) %><i class="icon-pencil"></i></h4> 
    </div>
      <div class="modal-body">
        <p style="float: left;"><img src="http://evernote.com/media/img/logos/evernote_logo_4c-sm.png" style="top:-30px"></p>
  <p><%= t(:evernote_permission_content) %></p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:not_now) %></a>
        <a href="auth/evernote" class="btn btn-primary"><%= t(:lets_go) %></a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modal-pair-google-home">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><%= t(:google_pairing) %><i class="icon-google-plus-sign"></i></h4> 
    </div>
      <div class="modal-body">
        <p style="float: left;"><img src="http://ssl.gstatic.com/s2/oz/images/logo/2x/googleplus_color_33-99ce54a16a32f6edc61a3e709eb61d31.png" style="top:-30px"></p>
  <p><%= t(:google_permission_content) %></p> 
      </div>
       <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" aria-hidden="true"><%= t(:not_now) %></a>
        <a href="auth/google_oauth2" class="btn btn-primary"><%= t(:lets_go) %></a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/personal_accounts/edit.html.erb
<h1>Editing personal_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @personal_account %> |
<%= link_to 'Back', personal_accounts_path %>

app/views/personal_accounts/index_v4.html.erb
<body class="sapUiBody" role="application">
    <div id="sample1" ></div>
    <div id="leftMenu" ></div>
</body>

app/views/personal_accounts/new.html.erb
<h1>New personal_account</h1>

<%= render 'form' %>

<%= link_to 'Back', personal_accounts_path %>

app/views/personal_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Note:</b>
  <%= @personal_account.note %>
</p>

<p>
  <b>Sound file:</b>
  <%= @personal_account.sound_file %>
</p>

<p>
  <b>User:</b>
  <%= @personal_account.user_id %>
</p>


<%= link_to 'Edit', edit_personal_account_path(@personal_account) %> |
<%= link_to 'Back', personal_accounts_path %>