config/routes.rb
LineAccess::Application.routes.draw do
  get "layout_builder/create"

  get "layout_builder/destroy"

  get "layout_builder/update"

  
  get "metric/show"
  get "metric/logInJSON"
  post "metric/logInJSON"
  get "metric/execJSON"
  post "metric/execJSON"

  match '/glasses/jarvixInterpreter', :controller => 'glasses', :action => 'jarvixInterpreter'
  resources :glasses

  resources :smartwatches

  match '/summaries/setLocation', :controller => 'summaries', :action => 'setLocation'
  match '/summaries/geoSettings', :controller => 'summaries', :action => 'geoSettings'
  match '/summaries/simulateMe', :controller => 'summaries', :action => 'simulateMe'
  match '/summaries/newOrigin', :controller => 'summaries', :action => 'newOrigin'
  match '/summaries/sendToAll', :controller => 'summaries', :action => 'sendToAll'
  match '/bot/callback', :controller => 'anet_devices', :action => 'fbbot'
  get '/summaries/call/:id', :controller => 'summaries', :action => 'showCallContents'
  match '/logout', :controller => 'summaries', :action => 'logout'
  resources :summaries

  
  resources :accounts

  resources :earthquakes

  resources :subscriptions

  resources :community

  resources :anet_logs

  resources :feed_readers

  resources :anet_values

  resources :anet_commands

  resources :dashboards

  get '/devices/claim', :controller=>'anet_devices', :action=> 'showClaim'
  get '/devices/add_board', :controller=>'anet_devices', :action=> 'showAdd'
  get '/devices/add_phone', :controller=>'anet_devices', :action=> 'showPhone'
  get '/devices/add_swatch', :controller=>'anet_devices', :action=> 'showSWatch'
  get '/devices/browser/:device', :controller=>'anet_devices', :action=> 'showBrowser'
  post '/devices/open/:device', :controller=>'anet_devices', :action=> 'showOpenFile'
  post '/devices/save/:device', :controller=>'anet_devices', :action=> 'showSaveFile'
  post '/devices/sync', :controller=>'anet_devices', :action=> 'alexa_sync'
  post '/devices/scan', :controller=>'anet_devices', :action=> 'alexa_scanning'
  post '/devices/dhcp', :controller=>'anet_devices', :action=> 'dhcp_process'
  match '/devices/send', :controller => 'anet_devices', :action => 'communication'
  match '/devices/camera/download', :controller => 'anet_devices', :action => 'camera_download'
  post '/devices/schedule', :controller=>'anet_devices', :action=> 'manage_schedule'
  match '/devices/pubsub', :controller=>'anet_devices', :action=> 'manage_pubsub'
  resources :anet_devices do
      post :sendToDevice, on: :collection 
  end
  
  resources :sys_user_phones

  resources :personal_accounts do
    post :changeLanguage, on: :collection
    post :likeIt, on: :collection
  end

  resources :authentications
  match '/auth/signup', :controller => 'authentications', :action => 'signup'
  get '/auth/signup/backwards', :controller => 'authentications', :action => 'backwards'
  match '/auth/webLogin', :controller => 'authentications', :action => 'webLogin'
  
  match '/auth/tokenize', :controller => 'authentications', :action => 'google_tokenize'
  match '/auth/v2/alexa/tokenize', :controller => 'authentications', :action => 'alexa_tokenize'
  post '/auth/cookie', :controller => 'authentications', :action => 'internal_token'
  match '/auth/assistant', :controller => 'authentications', :action => 'google_auth'
  match '/auth/alexapoc', :controller => 'authentications', :action => 'alexa_poc'
  match '/auth/alexa', :controller => 'authentications', :action => 'alexa_auth'
  get '/auth/messengerbot', :controller => 'authentications', :action => 'messenger_auth'
  post '/auth/messengerbot', :controller => 'authentications', :action => 'messenger_messages'
  match '/auth/:provider/callback' => 'authentications#create'

  get "/policy", to: "welcome#policy"
  get "/policy-es", to: "welcome#policy-es"

  match '/auth/v2/login', :controller => 'authentications', :action => 'loginv2'
  match '/auth/v2/verify', :controller => 'authentications', :action => 'internal_token'
  post '/auth/v2/user/avatar', :controller => 'authentications', :action => 'post_avatar_v2'
  post '/auth/v2/user/forgot', :controller => 'authentications', :action => 'post_forgot_v2'
  get '/auth/v2/user', :controller => 'authentications', :action => 'get_user_v2'
  put '/auth/v2/user', :controller => 'authentications', :action => 'put_user_v2'
  put '/auth/v2/user/pwd', :controller => 'authentications', :action => 'put_user_pwd_v2'
  match '/devices/v2/show', :controller=>'anet_devices', :action=> 'get_devices_v2'
  match '/devices/v2/recent_activity', :controller=>'anet_devices', :action=> 'get_recent_activity_v2'
  match '/location/v2/update', :controller=>'summaries', :action=> 'set_location_v2'
  match '/devices/v2/command/alexa', :controller=>'anet_devices', :action=> 'receive_alexa_payload_v2'
  match '/devices/v2/command/nest', :controller=>'anet_devices', :action=> 'receive_nest_payload_v2'
  match '/devices/v2/command/google', :controller=>'anet_devices', :action=> 'receive_google_payload_v2'
  match '/devices/v2/command/send', :controller=>'anet_devices', :action=> 'receive_api_payload_v2'
  match '/devices/v2/command/sendv2', :controller=>'anet_devices', :action=> 'sendToDevicev2'
  match '/devices/v2/public', :controller=>'anet_devices', :action=> 'get_public_devices_v2'
  match '/webhook/v2/from_email', :controller=>'anet_devices', :action=> 'receive_email_payload_v2'
  match '/assistant/v2/activity', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  post '/assistant/v2/link', :controller=>'authentications', :action=> 'post_assistant_link_v2'
  get '/assistant/v2/link', :controller=>'authentications', :action=> 'get_assistant_link_v2'
  match '/energy/v2/consumption/1day', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/7day', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/1month', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/12months', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/test/v2/test_1', :controller=>'anet_devices', :action=> 'random_test_v2'
  match '/test/v2/test_2', :controller=>'authentications', :action=> 'random_test2_v2'
  match '/devices/v2/:token/logs', :controller=>'anet_devices', :action=> 'get_device_logs_v2'
  post  '/devices/v2/:token/schedule', :controller=>'anet_devices', :action=> 'manage_schedule'
  post  '/devices/v2/:token/command', :controller=>'anet_commands', :action=> 'create'
  get  '/devices/v2/:token/status', :controller=>'anet_devices', :action=> 'get_status_v2'
  get  '/devices/v2/:token/state', :controller=>'anet_devices', :action=> 'get_state_v2'
  get  '/devices/v2/:token/screensaver', :controller=>'anet_devices', :action=> 'get_screensaver_v2'
  post  '/devices/v2/:token/screensaver', :controller=>'anet_devices', :action=> 'post_screensaver_v2'
  get  '/devices/v2/:token/props', :controller=>'anet_devices', :action=> 'get_props_v2'
  get  '/devices/v2/:token/prop/:id', :controller=>'anet_devices', :action=> 'get_prop_v2'
  get  '/devices/v2/:token/prop/:id/chart', :controller=>'anet_devices', :action=> 'get_prop_chart_v2'
  get  '/devices/v2/:token/prop/:id/chart/24hour', :controller=>'anet_devices', :action=> 'get_prop_chart_24h_v2'
  get  '/devices/v2/:token/prop/:id/chart/7day', :controller=>'anet_devices', :action=> 'get_prop_chart_7day_v2'
  get  '/devices/v2/:token/prop/:id/chart/monthly', :controller=>'anet_devices', :action=> 'get_prop_chart_month_v2'
  get  '/devices/v2/:token/command/show', :controller=>'anet_commands', :action=> 'show'
  get  '/devices/v2/:token/schedule/show', :controller=>'anet_devices', :action=> 'get_schedules_v2'
  delete  '/devices/v2/:token/schedule/:id', :controller=>'anet_devices', :action=> 'delete_schedule_v2'
  delete  '/devices/v2/:token/command/:id', :controller=>'anet_commands', :action=> 'destroy'
  post  '/layouts/v2', :controller=>'layout_builder', :action=> 'create'
  get  '/layouts/v2', :controller=>'layout_builder', :action=> 'show'
  delete  '/layouts/v2/:id', :controller=>'layout_builder', :action=> 'destroy'
  put  '/layouts/v2/:id', :controller=>'layout_builder', :action=> 'update'
  post  '/devices/v2/:token/fav', :controller=>'anet_devices', :action=> 'post_fav_v2'
  get  '/devices/v2/favs', :controller=>'anet_devices', :action=> 'get_fav_v2'
  post '/devices/v2/state/alexa', :controller=>'anet_devices', :action=> 'alexa_state_report_v2'
  get '/devices/v2/:token/state/suitch', :controller=>'anet_devices', :action=> 'suitch_state_report_v2'
  get '/edgar/test', :controller=>'anet_devices', :action=> 'test_api'
  post  '/chain/v2', :controller=>'chain_reaction', :action=> 'create'
  get  '/chain/v2', :controller=>'chain_reaction', :action=> 'show'
  delete  '/chain/v2/:id', :controller=>'chain_reaction', :action=> 'destroy'
  put  '/chain/v2/:id', :controller=>'chain_reaction', :action=> 'update'

  get '/devices/ssid/availables', :controller=>'anet_devices', :action=> 'getAvailableDevicePerSsid'
  post '/devices/ssid/owner', :controller=>'anet_devices', :action=> 'setIdOwnerToDevices'

  get '/devices/notifications', :controller=>'anet_devices', :action=> 'getDeviceNotifications'
  post '/devices/notifications/dismiss', :controller=>'anet_devices', :action=> 'post_notifications_dismiss'

  post '/devices/v2/findmy/create', :controller=>'anet_devices', :action=> 'findmy_create'
  post '/devices/v2/findmy/sensor', :controller=>'anet_devices', :action=> 'findmy_create_sensor'
  get '/devices/v2/findmy/all', :controller=>'anet_devices', :action=> 'get_findmy_all'
  get '/devices/v2/findmy/sensors', :controller=>'anet_devices', :action=> 'get_findmy_sensors'
  post '/devices/v2/findmy/located', :controller=>'anet_devices', :action=> 'findmy_located'
  get '/devices/v2/findmy/:token/soil', :controller=>'anet_devices', :action=> 'get_findmy_soil'

app/models/sys_user_phone.rb
class SysUserPhone < ActiveRecord::Base
  attr_accessible :number, :sys_phone_type, :sys_user
end

app/controllers/sys_user_phones_controller.rb
require 'sys_user.rb'
class SysUserPhonesController < ApplicationController
  # GET /sys_user_phones
  # GET /sys_user_phones.json
  def index
    @sys_user_phones = SysUserPhone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sys_user_phones }
    end
  end

  # GET /sys_user_phones/1
  # GET /sys_user_phones/1.json
  def show
    @sys_user_phone = SysUserPhone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sys_user_phone }
    end
  end

  # GET /sys_user_phones/new
  # GET /sys_user_phones/new.json
  def new
    @sys_user_phone = SysUserPhone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sys_user_phone }
    end
  end

  # GET /sys_user_phones/1/edit
  def edit
    @sys_user_phone = SysUserPhone.find(params[:id])
    render :layout => false
  end

  # POST /sys_user_phones
  # POST /sys_user_phones.json
  def create
    puts "----------------PHONE CREATE----------------"
    @sys_user_phone = SysUserPhone.new(params[:sys_user_phone])
    @sys_user_phone.sys_user=session[:activeUser].id
    respond_to do |format|
      if @sys_user_phone.save
        format.html { redirect_to "/personal_accounts", notice: 'A new phone was successfully created.' }
        format.json { render json: @sys_user_phone, status: :created, location: @sys_user_phone }
      else
        format.html { render action: "new" }
        format.json { render json: @sys_user_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sys_user_phones/1
  # PUT /sys_user_phones/1.json
  def update
    @sys_user_phone = SysUserPhone.find(params[:id])

    respond_to do |format|
      if @sys_user_phone.update_attributes(params[:sys_user_phone])
        format.html { redirect_to "/personal_accounts", notice: 'The phone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sys_user_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sys_user_phones/1
  # DELETE /sys_user_phones/1.json
  def destroy
    puts "-----destroy1-----"
    @sys_user_phone = SysUserPhone.find(params[:id])
    sid=@sys_user_phone.sys_user
    @sys_user_phone.destroy
    puts "-----destroy2-----"
    #recargar
    session[:activeUser]=Sys_User.find_by_user_id(sid)
    redirect_to "/personal_accounts", notice: 'The phone was successfully updated.'
    return
    puts "-----destroy3-----"
    respond_to do |format|
      format.html { redirect_to "/personal_accounts" }
      format.json { head :no_content }
    end
  end
end

app/helpers/sys_user_phones_helper.rb
module SysUserPhonesHelper
end

app/views/sys_user_phones/_form.html.erb
<%= simple_form_for @sys_user_phone, :html => {:multipart => true} do |f| %>
  
    
    
    <%= f.input :sys_phone_type, required:true,label:"Phone number type", input_html: { class:'form-control' },:collection => Sys_Phone_Type.all,:label_method => :description, :value_method => :id %>
    
    <%= f.input :number,required:true,label:"Phone number",input_html: { class:'form-control', placeholder:'(XXX) XXXX XXX'} %>
    
    <div class="checkbox m-t-lg">
    <button type="submit" class="btn btn-sm btn-success pull-right text-uc m-t-n-xs">Save now</button>     
    <% if request.env['PATH_INFO'].index("edit")!=nil %>     
    <%= link_to 'Delete', @sys_user_phone, :method=> :delete, data: { confirm: 'Are you sure?' },:class=>'btn btn-sm btn-danger pull-right text-uc m-t-n-xs' %>
    <% end %>
    </div>          
<% end %>
<% if request.env['PATH_INFO'].index("edit")!=nil %> 
<% telefonos=SysUserPhone.find_all_by_sys_user(session[:activeUser].id) %>
<% telefonosid=[] %>
<% telefonos.each do | singlePhone | %>
  <% telefonosid.push(" phone like '%"+singlePhone.number+"%' ") %>
<% end %>
<% totales=Sys_Phrase.where(telefonosid.join(" or ")).count %>
<% totalesWithPhone=Sys_Phrase.where("phone like '%"+@sys_user_phone.number.to_s+"%'").count %>
<% porcentage=0 %>
<% if totales>0 %>
<% porcentage=(totalesWithPhone*100)/totales %>
<% end %>

<section class="panel">
                    <header class="panel-heading">
                      Phone statistics
                    </header>
                    <div class="panel-body text-center">
                      <h4><%= totales %></h4>
                      <small class="text-muted block">Total commands/requests made to lineaccess</small>
                      <div class="inline">
                        <div class="easypiechart" data-percent="<%= porcentage %>" data-line-width="30" data-track-color="#eee" data-bar-color="#afcf6f" data-scale-color="#fff" data-loop="false" data-size="188">
                          <span class="h2"><%= totales %></span>%
                          <div class="easypie-text">made with this phone</div>
                        </div>
                      </div>                      
                    </div>
                    <div class="panel-footer"><small>% of avarage rate of commands</small></div>
                  </section>
                  <% end %>
                  <%= csrf_meta_tags %>

app/views/sys_user_phones/edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Edit your phone</h4>
    </div>
    <div class="modal-body">
      <%= render 'form' %>

 </div>
    
  </div>
</div>
<script type="text/javascript">
	updateRoundedCharts();
</script>

app/views/sys_user_phones/index.html.erb
<h1>Listing sys_user_phones</h1>

<table>
  <tr>
    <th>Sys user</th>
    <th>Sys phone type</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sys_user_phones.each do |sys_user_phone| %>
  <tr>
    <td><%= sys_user_phone.sys_user %></td>
    <td><%= sys_user_phone.sys_phone_type %></td>
    <td><%= sys_user_phone.number %></td>
    <td><%= link_to 'Show', sys_user_phone %></td>
    <td><%= link_to 'Edit', edit_sys_user_phone_path(sys_user_phone) %></td>
    <td><%= link_to 'Destroy', sys_user_phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sys user phone', new_sys_user_phone_path %>

app/views/sys_user_phones/new.html.erb
<h1>New sys_user_phone</h1>

<%= render 'form' %>

<%= link_to 'Back', sys_user_phones_path %>

app/views/sys_user_phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sys user:</b>
  <%= @sys_user_phone.sys_user %>
</p>

<p>
  <b>Sys phone type:</b>
  <%= @sys_user_phone.sys_phone_type %>
</p>

<p>
  <b>Number:</b>
  <%= @sys_user_phone.number %>
</p>


<%= link_to 'Edit', edit_sys_user_phone_path(@sys_user_phone) %> |
<%= link_to 'Back', sys_user_phones_path %>