config/routes.rb
LineAccess::Application.routes.draw do
  get "layout_builder/create"

  get "layout_builder/destroy"

  get "layout_builder/update"

  
  get "metric/show"
  get "metric/logInJSON"
  post "metric/logInJSON"
  get "metric/execJSON"
  post "metric/execJSON"

  match '/glasses/jarvixInterpreter', :controller => 'glasses', :action => 'jarvixInterpreter'
  resources :glasses

  resources :smartwatches

  match '/summaries/setLocation', :controller => 'summaries', :action => 'setLocation'
  match '/summaries/geoSettings', :controller => 'summaries', :action => 'geoSettings'
  match '/summaries/simulateMe', :controller => 'summaries', :action => 'simulateMe'
  match '/summaries/newOrigin', :controller => 'summaries', :action => 'newOrigin'
  match '/summaries/sendToAll', :controller => 'summaries', :action => 'sendToAll'
  match '/bot/callback', :controller => 'anet_devices', :action => 'fbbot'
  get '/summaries/call/:id', :controller => 'summaries', :action => 'showCallContents'
  match '/logout', :controller => 'summaries', :action => 'logout'
  resources :summaries

  
  resources :accounts

  resources :earthquakes

  resources :subscriptions

  resources :community

  resources :anet_logs

  resources :feed_readers

  resources :anet_values

  resources :anet_commands

  resources :dashboards

  get '/devices/claim', :controller=>'anet_devices', :action=> 'showClaim'
  get '/devices/add_board', :controller=>'anet_devices', :action=> 'showAdd'
  get '/devices/add_phone', :controller=>'anet_devices', :action=> 'showPhone'
  get '/devices/add_swatch', :controller=>'anet_devices', :action=> 'showSWatch'
  get '/devices/browser/:device', :controller=>'anet_devices', :action=> 'showBrowser'
  post '/devices/open/:device', :controller=>'anet_devices', :action=> 'showOpenFile'
  post '/devices/save/:device', :controller=>'anet_devices', :action=> 'showSaveFile'
  post '/devices/sync', :controller=>'anet_devices', :action=> 'alexa_sync'
  post '/devices/scan', :controller=>'anet_devices', :action=> 'alexa_scanning'
  post '/devices/dhcp', :controller=>'anet_devices', :action=> 'dhcp_process'
  match '/devices/send', :controller => 'anet_devices', :action => 'communication'
  match '/devices/camera/download', :controller => 'anet_devices', :action => 'camera_download'
  post '/devices/schedule', :controller=>'anet_devices', :action=> 'manage_schedule'
  match '/devices/pubsub', :controller=>'anet_devices', :action=> 'manage_pubsub'
  resources :anet_devices do
      post :sendToDevice, on: :collection 
  end
  
  resources :sys_user_phones

  resources :personal_accounts do
    post :changeLanguage, on: :collection
    post :likeIt, on: :collection
  end

  resources :authentications
  match '/auth/signup', :controller => 'authentications', :action => 'signup'
  get '/auth/signup/backwards', :controller => 'authentications', :action => 'backwards'
  match '/auth/webLogin', :controller => 'authentications', :action => 'webLogin'
  
  match '/auth/tokenize', :controller => 'authentications', :action => 'google_tokenize'
  match '/auth/v2/alexa/tokenize', :controller => 'authentications', :action => 'alexa_tokenize'
  post '/auth/cookie', :controller => 'authentications', :action => 'internal_token'
  match '/auth/assistant', :controller => 'authentications', :action => 'google_auth'
  match '/auth/alexapoc', :controller => 'authentications', :action => 'alexa_poc'
  match '/auth/alexa', :controller => 'authentications', :action => 'alexa_auth'
  get '/auth/messengerbot', :controller => 'authentications', :action => 'messenger_auth'
  post '/auth/messengerbot', :controller => 'authentications', :action => 'messenger_messages'
  match '/auth/:provider/callback' => 'authentications#create'

  get "/policy", to: "welcome#policy"
  get "/policy-es", to: "welcome#policy-es"

  match '/auth/v2/login', :controller => 'authentications', :action => 'loginv2'
  match '/auth/v2/verify', :controller => 'authentications', :action => 'internal_token'
  post '/auth/v2/user/avatar', :controller => 'authentications', :action => 'post_avatar_v2'
  post '/auth/v2/user/forgot', :controller => 'authentications', :action => 'post_forgot_v2'
  get '/auth/v2/user', :controller => 'authentications', :action => 'get_user_v2'
  put '/auth/v2/user', :controller => 'authentications', :action => 'put_user_v2'
  put '/auth/v2/user/pwd', :controller => 'authentications', :action => 'put_user_pwd_v2'
  match '/devices/v2/show', :controller=>'anet_devices', :action=> 'get_devices_v2'
  match '/devices/v2/recent_activity', :controller=>'anet_devices', :action=> 'get_recent_activity_v2'
  match '/location/v2/update', :controller=>'summaries', :action=> 'set_location_v2'
  match '/devices/v2/command/alexa', :controller=>'anet_devices', :action=> 'receive_alexa_payload_v2'
  match '/devices/v2/command/nest', :controller=>'anet_devices', :action=> 'receive_nest_payload_v2'
  match '/devices/v2/command/google', :controller=>'anet_devices', :action=> 'receive_google_payload_v2'
  match '/devices/v2/command/send', :controller=>'anet_devices', :action=> 'receive_api_payload_v2'
  match '/devices/v2/command/sendv2', :controller=>'anet_devices', :action=> 'sendToDevicev2'
  match '/devices/v2/public', :controller=>'anet_devices', :action=> 'get_public_devices_v2'
  match '/webhook/v2/from_email', :controller=>'anet_devices', :action=> 'receive_email_payload_v2'
  match '/assistant/v2/activity', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  post '/assistant/v2/link', :controller=>'authentications', :action=> 'post_assistant_link_v2'
  get '/assistant/v2/link', :controller=>'authentications', :action=> 'get_assistant_link_v2'
  match '/energy/v2/consumption/1day', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/7day', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/1month', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/energy/v2/consumption/12months', :controller=>'system_activities', :action=> 'get_assistant_activity_v2'
  match '/test/v2/test_1', :controller=>'anet_devices', :action=> 'random_test_v2'
  match '/test/v2/test_2', :controller=>'authentications', :action=> 'random_test2_v2'
  match '/devices/v2/:token/logs', :controller=>'anet_devices', :action=> 'get_device_logs_v2'
  post  '/devices/v2/:token/schedule', :controller=>'anet_devices', :action=> 'manage_schedule'
  post  '/devices/v2/:token/command', :controller=>'anet_commands', :action=> 'create'
  get  '/devices/v2/:token/status', :controller=>'anet_devices', :action=> 'get_status_v2'
  get  '/devices/v2/:token/state', :controller=>'anet_devices', :action=> 'get_state_v2'
  get  '/devices/v2/:token/screensaver', :controller=>'anet_devices', :action=> 'get_screensaver_v2'
  post  '/devices/v2/:token/screensaver', :controller=>'anet_devices', :action=> 'post_screensaver_v2'
  get  '/devices/v2/:token/props', :controller=>'anet_devices', :action=> 'get_props_v2'
  get  '/devices/v2/:token/prop/:id', :controller=>'anet_devices', :action=> 'get_prop_v2'
  get  '/devices/v2/:token/prop/:id/chart', :controller=>'anet_devices', :action=> 'get_prop_chart_v2'
  get  '/devices/v2/:token/prop/:id/chart/24hour', :controller=>'anet_devices', :action=> 'get_prop_chart_24h_v2'
  get  '/devices/v2/:token/prop/:id/chart/7day', :controller=>'anet_devices', :action=> 'get_prop_chart_7day_v2'
  get  '/devices/v2/:token/prop/:id/chart/monthly', :controller=>'anet_devices', :action=> 'get_prop_chart_month_v2'
  get  '/devices/v2/:token/command/show', :controller=>'anet_commands', :action=> 'show'
  get  '/devices/v2/:token/schedule/show', :controller=>'anet_devices', :action=> 'get_schedules_v2'
  delete  '/devices/v2/:token/schedule/:id', :controller=>'anet_devices', :action=> 'delete_schedule_v2'
  delete  '/devices/v2/:token/command/:id', :controller=>'anet_commands', :action=> 'destroy'
  post  '/layouts/v2', :controller=>'layout_builder', :action=> 'create'
  get  '/layouts/v2', :controller=>'layout_builder', :action=> 'show'
  delete  '/layouts/v2/:id', :controller=>'layout_builder', :action=> 'destroy'
  put  '/layouts/v2/:id', :controller=>'layout_builder', :action=> 'update'
  post  '/devices/v2/:token/fav', :controller=>'anet_devices', :action=> 'post_fav_v2'
  get  '/devices/v2/favs', :controller=>'anet_devices', :action=> 'get_fav_v2'
  post '/devices/v2/state/alexa', :controller=>'anet_devices', :action=> 'alexa_state_report_v2'
  get '/devices/v2/:token/state/suitch', :controller=>'anet_devices', :action=> 'suitch_state_report_v2'
  get '/edgar/test', :controller=>'anet_devices', :action=> 'test_api'
  post  '/chain/v2', :controller=>'chain_reaction', :action=> 'create'
  get  '/chain/v2', :controller=>'chain_reaction', :action=> 'show'
  delete  '/chain/v2/:id', :controller=>'chain_reaction', :action=> 'destroy'
  put  '/chain/v2/:id', :controller=>'chain_reaction', :action=> 'update'

  get '/devices/ssid/availables', :controller=>'anet_devices', :action=> 'getAvailableDevicePerSsid'
  post '/devices/ssid/owner', :controller=>'anet_devices', :action=> 'setIdOwnerToDevices'

  get '/devices/notifications', :controller=>'anet_devices', :action=> 'getDeviceNotifications'
  post '/devices/notifications/dismiss', :controller=>'anet_devices', :action=> 'post_notifications_dismiss'

  post '/devices/v2/findmy/create', :controller=>'anet_devices', :action=> 'findmy_create'
  post '/devices/v2/findmy/sensor', :controller=>'anet_devices', :action=> 'findmy_create_sensor'
  get '/devices/v2/findmy/all', :controller=>'anet_devices', :action=> 'get_findmy_all'
  get '/devices/v2/findmy/sensors', :controller=>'anet_devices', :action=> 'get_findmy_sensors'
  post '/devices/v2/findmy/located', :controller=>'anet_devices', :action=> 'findmy_located'
  get '/devices/v2/findmy/:token/soil', :controller=>'anet_devices', :action=> 'get_findmy_soil'

app/models/anet_device.rb
class AnetDevice < ActiveRecord::Base
  attr_accessible :description, :id, :id_owner, :is_public, :location, :object, :secret_token, :token,:likes,:cliente, :version
  attr_accessible :notify_hangout, :notify_fb, :notify_email, :notify_twitter, :notify_fbinbox,:mip, :notify_telegram
  has_many :system_activities
end

app/helpers/anet_devices_helper.rb
module AnetDevicesHelper
end

app/views/anet_devices/_form.html.erb
<% singleWindowNumber=Random.rand(99) %>

<% if request.env['PATH_INFO'].index("edit")!=nil %>
<script>
    generateSparkline(false);
    </script>
<section class="panel">
                <header class="panel-heading text-right bg-light">
                  <ul class="nav nav-tabs pull-left">
                    <li class="active"><a href="#messages-<%= singleWindowNumber %>" data-toggle="tab"><i class="icon-comments text-default"></i><%= t(:spoken_commands) %></a></li>
                    <li><a href="#profile-<%= singleWindowNumber %>" data-toggle="tab"><i class="icon-cog text-default"></i><%= t(:settings) %></a></li>
                    <li><a href="#schedule-<%= singleWindowNumber %>" data-toggle="tab"><i class="icon-cog text-default"></i><%= t(:schedule) %></a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-exclamation-sign text-default"></i><%= t(:need_help) %><b class="caret"></b></a>
                      <ul class="dropdown-menu text-left">
                        <li><a href="https://www.facebook.com/suitch.co" data-toggle="tab">https://www.facebook.com/suitch.co</a></li>
                        <li><a href="https://twitter.com/suitch_" data-toggle="tab">https://twitter.com/suitch_</a></li>
                      </ul>
                    </li>
                  </ul>
                  <span class="hidden-sm"><%= t(:edit_and) %></span>
                </header>
<div class="panel-body">
 <div class="tab-content"> 
    <div class="tab-pane fade" id="schedule-<%= singleWindowNumber %>">
        <div class="panel">
        <form method="POST" action="/devices/schedule">
        <input type="hidden" id="device_id" name="device_id" value="<%= @anet_device.id %>">
        <input type="hidden" id="authenticity_token_id" name="authenticity_token" value="<%= form_authenticity_token.to_s %>">
          <div class="row">
            <div class='col-sm-5'>
              <div class="form-group">
                <label for="sel1">Available commands:</label>
                <select class="form-control" id="sel1" name="command">
                <option value="---">---</option>
                <% @anet_commands.each do |singleCommand| %>
                  <option value="<%= singleCommand.id %>"><%= singleCommand.command  %> (<%= singleCommand.command_data %>)</option>
                <% end %>
                </select>
              </div>
            </div>
            <div class='col-sm-5'>
                <div class="form-group">
                <label for="sel1">Automated at:</label>
                    <div class='input-group date' id='datetimepicker1' >
                        <input type='text' class="form-control" name="schedule"/>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-sm-2'>
                <div class="form-group">
                <label for="sel1">Action:</label>
                  <button type="submit" class="btn btn-primary btn-xs">Create</button>
                </div>
            </div>  
          <script type="text/javascript">
              $(function () {
                  $('#datetimepicker1').datetimepicker({format: 'YYYY-MM-DD hh:mm A'});
              });
          </script>
          </div>
          </form>
        </div>

        <section class="panel">
          <header class="panel-heading"><% t(:stats) %></header>
          <table class="table table-striped m-b-none text-sm">
            <thead>
              <tr>
                
                <th width="25"><%= t(:command) %></th>
                <th width="25"><%= t(:schedule) %></th>                    
                <th width="25"><%= t(:actions) %></th>
              </tr>
            </thead>
            <tbody>
                <% @anet_schedules.each do |singleSchedule| %>
                <% comando = AnetCommand.where(:id => singleSchedule.command ).last %>
                
              <tr>                    
                <td>
                  <% if comando != nil %>
                    <%= comando.command_data %>
                  <% end %>
                </td>
                <td class="text-success">
                <%= singleSchedule.schedule %>
                </td>
                <td>
                  <%= t(:delete) %>
                </td>
              </tr>
                <% end %>
            </tbody>
          </table>
        </section>
    </div>             
    <div class="tab-pane fade active in" id="messages-<%= singleWindowNumber %>">
        <div class="panel">
                  <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                      <%= t(:click_to_add) %>
                    </a>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body text-sm">
                        <%= render "anet_commands/form" %>
                    </div>
                  </div>
                </div>
        <section class="panel">
                    <header class="panel-heading"><%= t(:stats) %></header>
                    <table class="table table-striped m-b-none text-sm">
                      <thead>
                        <tr>
                          <th width="70"><%= t(:plot) %></th>
                          <th width="25"><%= t(:command) %></th>
                          <!-- th width="25"><%= t(:schedule) %></th -->                    
                          <th><%= t(:when_executed) %></th>
                          <th width="60"><%= t(:actions) %></th>
                        </tr>
                      </thead>
                      <tbody>
                          <% @anet_commands.each do |singleCommand| %>
                          <% valoresSpark=[] %>
                          <% valores=AnetValue.select(:value).where(:command_id=>singleCommand.id).limit(15) %>
                          <% valores.each do |singleCommandValue| %>
                          <% valoresSpark.push(singleCommandValue.value) %>
                          <% end %>
                        <tr>                    
                          <td>
                            <div class="sparkline" data-bar-color="#5cb85c" data-type="bar" data-height="19"><!-- <%= valoresSpark.join(",") %> --></div>
                          </td>
                          <td><%= singleCommand.command_data %></td>
                          <% if singleCommand.on_time==nil %>
                          <!-- td>none</td -->
                          <% else %>
                          <!-- td><%= Time.at(singleCommand.on_time.to_i+6.hour.to_i).strftime("%I:%M %p") %></td -->
                          <% end %>
                          
                          <td class="text-success">
                              <%= t(:iwant) %> <%= singleCommand.command %> <%= @anet_device.object %> <%= t(:from) %> <%= @anet_device.location %>
                          </td>
                          <td><a href="#" ><%= t(:delete) %> <i class="icon-remove"></i></a><br> <a href="javascript:sendit('<%= @anet_device.token %>','<%= singleCommand.command_data %>')" > <%= t(:test) %> <i class="icon-bolt"></i></a></td>
                        </tr>
                          <% end %>
                      </tbody>
                    </table>
                  </section>

                
        
     </div>
    <div class="tab-pane fade" id="profile-<%= singleWindowNumber %>">
  <% end %> 
<%= simple_form_for @anet_device, :html=> { class: 'form' } do |f| %>  
  <div  >
    <%= f.input :object,:as=>:string,label:"Object",input_html: { class:'form-control',placeholder:'Give it a name like "light" or "door" or "motor"' } %>
  </div>
  <div  >
    <%= f.input :location,:as=>:string,label:"Location",input_html: { class:'form-control',placeholder:'Give it a location like "kitchen" or "office" or "garage"' } %>
  </div>
  <div  >
    <%= f.input :description,label:"Description",input_html: { class:'form-control',rows:"6",placeholder:'The description is for you, add notes here' } %>
  </div>
  <% if request.env['PATH_INFO'].index("edit")!=nil %>
  <div  >
    <%= f.input :token,:as=>:string,label:"Token",input_html:{ class:'form-control',placeholder:'The token is generated when saving'},disabled:true %>
  </div>
  <div  >
      
    <%= f.input :secret_token,:as=>:string,label:"Token secret",input_html:{ class:'form-control',placeholder:'The token password is generated when saving'},disabled:true %>
  </div>
  <% end %>
  <div class="checkbox m-t-lg">
  <label>
    <%= f.input_field :is_public,:as=>:boolean,inline_label:"Is this device available from other arduinos/raspberries?",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
    </label>
  </div>
  <strong>Check the type of notifications you would like to receive when connecting/disconnecting</strong>
 <!--  <div class="checkbox m-t-lg">
    <%= f.input_field :notify_hangout,:as=>:boolean,inline_label:"Hangout",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
  </div> -->
  <!-- div class="checkbox m-t-lg">
    <%= f.input_field :notify_fb,:as=>:boolean,inline_label:"Facebook wall",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
  </div -->
  <div class="checkbox m-t-lg">
    <%= f.input_field :notify_email,:as=>:boolean,inline_label:"Email",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
  </div>
  <div class="checkbox m-t-lg">
    <%= f.input_field :notify_twitter,:as=>:boolean,inline_label:"Twitter",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
  </div>
  <div class="checkbox m-t-lg">
    <%= f.input_field :notify_telegram,:as=>:boolean,inline_label:"Telegram",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
  </div>
  <div class="checkbox m-t-lg">
    <%= f.input_field :notify_fbinbox,:as=>:boolean,inline_label:"Facebook Messenger",input_html:{ class:'form-control pull-right text-uc m-t-n-xs'} %>
  </div>
  
  
 <div class="checkbox m-t-lg">
    <button type="submit" class="btn btn-sm btn-success pull-right text-uc m-t-n-xs"><%= t(:save_now) %></button>     
    <% if request.env['PATH_INFO'].index("edit")!=nil %>     
    <%= link_to 'Delete', @anet_device, :method=> :delete, data: { confirm: 'Are you sure?' },:class=>'btn btn-sm btn-danger pull-right text-uc m-t-n-xs' %>
    <% end %>
    </div>     
<% end %>
        <% if request.env['PATH_INFO'].index("edit")!=nil %>
        </div>
     <div class="tab-pane fade" id="dropdown<%= singleWindowNumber %>">dropdown1</div>
    <div class="tab-pane fade" id="dropdown<%= singleWindowNumber %>">dropdown2</div>
  </div>
</div>
      <% end %>
              </section>

app/views/anet_devices/browseFiles.html.erb
<script>

    var pusher = new Pusher('a41aed5f65a8c69c5f0a', {
      cluster: 'us2',
      forceTLS: true
    });

    var channel = pusher.subscribe('<%= @device %>');
    var currentFile = "";
    channel.bind('open-file', function(data) {
      var tmpSection = window.atob(data.message);
      console.log(tmpSection.indexOf("openFile=<<<BEGIN"))
      if (tmpSection.indexOf("openFile=<<<BEGIN") == 0){
        currentFile = tmpSection;
      } else {
        currentFile = currentFile + tmpSection;
      }
      $("#fileContent").val(currentFile.substring(17, currentFile.indexOf("<<<END\n\r")));
    });

    function getSingleFile(){
        var x = document.getElementById("archivos").value;
        document.getElementById("fileTitle").value=x;
        $.post("/devices/open/<%= @device %>.json",
        {
            file: x,
            device: "<%= @device %>",
            utf8:"✓",
            authenticity_token:'<%= form_authenticity_token.to_s %>'
        },
        function(data, status){
            
        });
    }
    function saveFile(){
      $("#my-save-file").prop("disabled",true);
      $("#fileContent").prop("disabled",true);
        $.post("/devices/save/<%= @device %>.json",
        {
            
            file: document.getElementById("fileTitle").value,
            device: "<%= @device %>",
            contents: window.btoa(document.getElementById("fileContent").value),
            utf8:"✓",
            authenticity_token:'<%= form_authenticity_token.to_s %>'
        },
        function(data, status){
          $("#my-save-file").prop("disabled",false);
          $("#fileContent").prop("disabled",false);
          alert("File has been saved");
        });
    }
  </script>
<div class="modal fade in" id="modal-browse-files" style="display: block;">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"><%= t(:device) %> <i class="icon-phone"></i></h4> 
  </div>
    <div class="modal-body">
      


  <link href='https://fonts.googleapis.com/css?family=Roboto:300|Text+Me+One' rel='stylesheet' type='text/css'>
  <style type="text/css">
  
 
a:link {
    color: #dfe5eb;
    text-decoration: none;
}

/* visited link */
a:visited {
    color: #dfe5eb;
    text-decoration: none;
}

/* mouse over link */
a:hover {
    color: #fff;
    text-decoration: none;
}

/* selected link */
a:active {
    color: #dfe5eb;
    text-decoration: none;
}
*::-moz-selection, *::selection {
  color: rgba(0, 0, 0, 0.8);
  background: rgba(255, 255, 255, 0.5);
}
form {
  width: 100%;
  color: #fff;
  margin: 0 auto;
  margin-top: 1em;
}

/*
 * Title: input
 */

input[type="text"],textarea {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  border: none;
  font: 1.1em/1.75em 'Text Me One', sans-serif;
  outline: none;
  word-spacing: -.25em;
  position: relative;
  background-color: transparent;
  border-bottom: 0.05em solid rgba(169, 147, 147, 0.4);
  color: #999;
  width: 100%;
  margin-bottom: .2em;
  font-variant: small-caps;
  font-size: 1.5em;
  line-height: 1em;
  -moz-transition: box-shadow 0.55s ease-in-out;
  -o-transition: box-shadow 0.55s ease-in-out;
  -webkit-transition: box-shadow 0.55s ease-in-out;
  transition: box-shadow 0.55s ease-in-out;
}
input[type="text"]:focus,textarea:focus {
  box-shadow: 0 -1em 5em -0.2em rgba(245, 255, 213, 1), 0 1em 5em -0.2em rgba(245, 255, 213, 1);
}



  </style>



<div class="wrapper" id="mywrapper">
  <section>
    <h1>File editor</h1>
    <h2>Browse your files, edit and delete them. Easy peasy</h2>
    
    <form method="get" action="">
<table style="width:100%">
  <tr>
    <td><input type="text" name="title" autocomplete="off" spellcheck="false" id="fileTitle"></td>
    <td>

    <select style="height:100%;" id="archivos" onchange="getSingleFile();">
    <% @files.each do |singleFile| %>
        <option value="<%= singleFile["file"] %>"><%= singleFile["file"] %>/<%= singleFile["size"] %> bytes</option>'; 
    <% end %>
    </select>
</td> 
  </tr>
</table>
    <textarea data-type="1" name="text" rows="5" spellcheck="false" style="height:400px" id="fileContent"></textarea>
    <table style="width:30%">
  <tr>
    <td><button type="button" data-type="2" contenteditable="true" spellcheck="false" style="width:70px" onclick="saveFile();" id="my-save-file">Save</button></td>
  </tr>
</table>
  </form>
  </section>
</div>

    
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div>

app/views/anet_devices/index.html.erb
<h1>Listing anet_devices</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Description</th>
    <th>Location</th>
    <th>Object</th>
    <th>Token</th>
    <th>Secret token</th>
    <th>Id owner</th>
    <th>Is public</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anet_devices.each do |anet_device| %>
  <tr>
    <td><%= anet_device.id %></td>
    <td><%= anet_device.description %></td>
    <td><%= anet_device.location %></td>
    <td><%= anet_device.object %></td>
    <td><%= anet_device.token %></td>
    <td><%= anet_device.secret_token %></td>
    <td><%= anet_device.id_owner %></td>
    <td><%= anet_device.is_public %></td>
    <td><%= link_to 'Show', anet_device %></td>
    <td><%= link_to 'Edit', edit_anet_device_path(anet_device) %></td>
    <td><%= link_to 'Destroy', anet_device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anet device', new_anet_device_path %>

app/views/anet_devices/new.html.erb
<h1>New anet_device</h1>

<%= render 'form' %>

<%= link_to 'Back', anet_devices_path %>

app/views/anet_devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @anet_device.id %>
</p>

<p>
  <b>Description:</b>
  <%= @anet_device.description %>
</p>

<p>
  <b>Location:</b>
  <%= @anet_device.location %>
</p>

<p>
  <b>Object:</b>
  <%= @anet_device.object %>
</p>

<p>
  <b>Token:</b>
  <%= @anet_device.token %>
</p>

<p>
  <b>Secret token:</b>
  <%= @anet_device.secret_token %>
</p>

<p>
  <b>Id owner:</b>
  <%= @anet_device.id_owner %>
</p>

<p>
  <b>Is public:</b>
  <%= @anet_device.is_public %>
</p>


<%= link_to 'Edit', edit_anet_device_path(@anet_device) %> |
<%= link_to 'Back', anet_devices_path %>